create table if not exists informasi_kampus (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text,
  isi text not null,
  created_at timestamp with time zone default now()
);

create table if not exists wiki_kampus (
  id bigint generated by default as identity primary key,
  judul text not null,
  kategori text,
  isi text not null,
  created_at timestamp with time zone default now()
);

create table if not exists lowongan_kerja (
  id bigint generated by default as identity primary key,
  posisi text not null,
  perusahaan text not null,
  lokasi text,
  deskripsi text,
  link text,
  created_at timestamp with time zone default now()
);

alter table informasi_kampus enable row level security;
alter table wiki_kampus enable row level security;
alter table lowongan_kerja enable row level security;

create policy "Public read informasi" on informasi_kampus for select using (true);
create policy "Public read wiki" on wiki_kampus for select using (true);
create policy "Public read lowongan" on lowongan_kerja for select using (true);

create policy "Admin insert informasi" on informasi_kampus for insert to authenticated with check (true);
create policy "Admin update informasi" on informasi_kampus for update to authenticated using (true) with check (true);
create policy "Admin delete informasi" on informasi_kampus for delete to authenticated using (true);

create policy "Admin insert wiki" on wiki_kampus for insert to authenticated with check (true);
create policy "Admin update wiki" on wiki_kampus for update to authenticated using (true) with check (true);
create policy "Admin delete wiki" on wiki_kampus for delete to authenticated using (true);

create policy "Admin insert lowongan" on lowongan_kerja for insert to authenticated with check (true);
create policy "Admin update lowongan" on lowongan_kerja for update to authenticated using (true) with check (true);
create policy "Admin delete lowongan" on lowongan_kerja for delete to authenticated using (true);
