create table if not exists public.kosan (
  id bigint generated by default as identity primary key,
  nama text not null,
  tipe text not null check (tipe in ('Putra', 'Putri', 'Campur')),
  area text not null,
  alamat text,
  harga_bulanan numeric not null check (harga_bulanan >= 0),
  fasilitas text,
  deskripsi text,
  gambar text,
  kontak text,
  tersedia boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists kosan_created_at_idx on public.kosan (created_at desc);
create index if not exists kosan_area_idx on public.kosan (area);

alter table public.kosan enable row level security;

create policy "Kosan dapat dibaca publik"
on public.kosan for select
to anon, authenticated
using (true);

create policy "Admin dapat menambah kosan"
on public.kosan for insert
to authenticated
with check (true);

create policy "Admin dapat mengubah kosan"
on public.kosan for update
to authenticated
using (true)
with check (true);

create policy "Admin dapat menghapus kosan"
on public.kosan for delete
to authenticated
using (true);
